 ---
A:
  type: App
  ready: '2021-06-25'
  templates:
    0: "[:ua, :user_id, :app_id]"
    1: "[:oa, :org_id, :app_id]"
ABCFE:
  type: AutomaticBaseChangeFailedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rabcfe, :repo_id, :issue_id, :automatic_base_change_failed_event_id]"
ABCSE:
  type: AutomaticBaseChangeSucceededEvent
  ready: '2021-09-01'
  templates:
    0: "[:rabcse, :repo_id, :issue_id, :automatic_base_change_succeeded_event_id]"
AE:
  type: AssignedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rae, :repo_id, :issue_id, :assigned_event_id]"
AMDE:
  type: AutoMergeDisabledEvent
  ready: '2021-09-01'
  templates:
    0: "[:amde, :repo_id, :issue_id, :id]"
AMEE:
  type: AutoMergeEnabledEvent
  ready: '2021-09-01'
  templates:
    0: "[:amee, :repo_id, :issue_id, :id]"
AREE:
  type: AutoRebaseEnabledEvent
  ready: '2021-09-01'
  templates:
    0: "[:aree, :repo_id, :issue_id, :id]"
ASEE:
  type: AutoSquashEnabledEvent
  ready: '2021-09-01'
  templates:
    0: "[:asee, :repo_id, :issue_id, :id]"
ATMQE:
  type: AddedToMergeQueueEvent
  ready: '2021-09-01'
  templates:
    0: "[:amqe, :repo_id, :issue_id, :id]"
ATPE:
  type: AddedToProjectEvent
  ready: '2021-09-01'
  templates:
    0: "[:ratpe, :repo_id, :issue_id, :added_to_project_event_id]"
B:
  type: Blob
  ready: '2021-09-21'
  templates:
    0: "[:rb, :repo_id, :oid]"
BOT:
  type: Bot
  ready: '2021-09-30'
  templates:
    0: "[:b, :bot_id]"
BPR:
  type: BranchProtectionRule
  ready: '2021-09-14'
  templates:
    0: "[:bpr, :repository_id, :id]"
BRCE:
  type: BaseRefChangedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rbrce, :repo_id, :issue_id, :base_ref_changed_event_id]"
BRDE:
  type: BaseRefDeletedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rbrde, :repo_id, :issue_id, :base_ref_deleted_event_id]"
BRFPE:
  type: BaseRefForcePushedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rbrfpe, :repo_id, :issue_id, :base_ref_force_pushed_event_id]"
C:
  type: Commit
  ready: '2021-09-21'
  templates:
    0: "[:rc, :repo_id, :oid]"
CC:
  type: CommitComment
  ready: '2021-09-01'
  templates:
    0: "[:rcc, :repo_id, :commit_comment_id]"
CCT:
  type: CommitCommentThread
  ready: '2021-09-14'
  templates:
    0: "[:r, :repository_id, :commit_oid, :path, :position]"
CDE:
  type: CommentDeletedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rcde, :repo_id, :issue_id, :comment_deleted_event_id]"
CE:
  type: ClosedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rce, :repo_id, :issue_id, :closed_event_id]"
CNTIE:
  type: ConvertedNoteToIssueEvent
  ready: '2021-09-01'
  templates:
    0: "[:rcntie, :repo_id, :issue_id, :converted_note_to_issue_event_id]"
COC:
  type: CodeOfConduct
  ready: '2021-09-01'
  templates:
    0: "[:rcoc, :repo_id, :code_of_conduct_id]"
COE:
  type: ConnectedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rce, :repo_id, :issue_id, :connected_event_id]"
CR:
  type: CheckRun
  ready: '2021-09-07'
  templates:
    0: "[:rcr, :repo_id, :check_run_id]"
CS:
  type: CheckSuite
  ready: '2021-09-01'
  templates:
    0: "[:rcs, :repo_id, :check_suite_id]"
CTDE:
  type: ConvertToDraftEvent
  ready: '2021-09-01'
  templates:
    0: "[:rctde, :repo_id, :issue_id, :convert_to_draft_event_id]"
CWE:
  type: CWE
  ready: '2021-09-01'
  templates:
    0: "[:c, :id]"
D:
  type: Discussion
  ready: nil
  templates:
    0: "[:d, :repository_id, :id]"
DC:
  type: DiscussionComment
  ready: '2021-08-30'
  templates:
    0: "[:rdc, :repo_id, :discussion_comment_id]"
DE:
  type: Deployment
  ready: '2021-07-02'
  templates:
    0: "[:rde, :repo_id, :deployment_id]"
DECE:
  type: DeploymentEnvironmentChangedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rdece, :repo_id, :issue_id, :deployment_environment_changed_event_id]"
DEE:
  type: DeployedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rde, :repo_id, :issue_id, :deployed_event_id]"
DEME:
  type: DemilestonedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rde, :repo_id, :issue_id, :demilestoned_event_id]"
DES:
  type: DeploymentStatus
  ready: '2021-07-02'
  templates:
    0: "[:rdes, :repo_id, :deployment_status_id]"
DGM:
  type: DependencyGraphManifest
  ready: '2021-09-14'
  templates:
    0: "[:dgm, :repo_id, :id]"
DIC:
  type: DiscussionCategory
  ready: '2021-07-02'
  templates:
    0: "[:rdc, :repo_id, :id]"
DIE:
  type: DisconnectedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rde, :repo_id, :issue_id, :disconnected_event_id]"
EAI:
  type: EnterpriseAdministratorInvitation
  ready: '2021-06-18'
  templates:
    0: "[:eeai, :enterprise_id, :enterprise_administrator_invitation_id]"
EI:
  type: ExternalIdentity
  ready: '2021-07-02'
  templates:
    0: "[:eipei, :enterprise_id, :enterprise_identity_provider_id, :external_identity_id]"
    1: "[:oipei, :org_id, :org_identity_provider_id, :external_identity_id]"
EIP:
  type: EnterpriseIdentityProvider
  ready: '2021-05-15'
  templates:
    0: "[:eeip, :enterprise_id, :enterprise_identity_provider_id]"
ESI:
  type: EnterpriseServerInstallation
  ready: '2021-09-07'
  templates:
    0: "[:u, :user_id, :id]"
    1: "[:b, :business_id, :id]"
ESUA:
  type: EnterpriseServerUserAccount
  ready: '2021-09-07'
  templates:
    0: "[:esua, :enterprise_installation_id, :id]"
EUA:
  type: EnterpriseUserAccount
  ready: '2021-06-18'
  templates:
    0: "[:eeua, :enterprise_id, :enterprise_user_account_id]"
G:
  type: Gist
  ready: '2021-09-21'
  templates:
    0: "[:g, :user_id, :repo_name]"
GC:
  type: GistComment
  ready: '2021-09-21'
  templates:
    0: "[:ugc, :user_id, :gist_id, :id]"
HRDE:
  type: HeadRefDeletedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rhrde, :repo_id, :issue_id, :head_ref_deleted_event_id]"
HRFPE:
  type: HeadRefForcePushedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rhrfpe, :repo_id, :issue_id, :head_ref_force_pushed_event_id]"
HRRE:
  type: HeadRefRestoredEvent
  ready: '2021-09-01'
  templates:
    0: "[:rhrre, :repo_id, :issue_id, :head_ref_restored_event_id]"
I:
  type: Issue
  ready: nil
  templates:
    0: "[:i, :repo_id, :id]"
IALE:
  type: IpAllowListEntry
  ready: '2021-07-10'
  templates:
    0: "[:eiale, :enterprise_id, :ip_allow_list_entry_id]"
    1: "[:oiale, :org_id, :ip_allow_list_entry_id]"
    2: "[:uaiale, :user_id, :application_id, :ip_allow_list_entry_id]"
    3: "[:oaiale, :org_id, :application_id, :ip_allow_list_entry_id]"
IC:
  type: IssueComment
  ready: '2021-07-16'
  templates:
    0: "[:ric, :repo_id, :issue_comment_id]"
IM:
  type: Import
  ready: '2021-09-01'
  templates:
    0: "[:ui, :user_id, :import_id]"
L:
  type: License
  ready: '2021-09-28'
  templates:
    0: "[:l, :license_key]"
LA:
  type: Label
  ready: '2021-09-21'
  templates:
    0: "[:rl, :repo_id, :label_id]"
LAN:
  type: Language
  ready: '2021-09-07'
  templates:
    0: "[:l, :language_id]"
LE:
  type: LabeledEvent
  ready: '2021-09-01'
  templates:
    0: "[:rle, :repo_id, :issue_id, :labeled_event_id]"
LM:
  type: LegacyMigration
  ready: '2021-09-07'
  templates:
    0: "[:um, :user_id, :id]"
    1: "[:om, :org_id, :id]"
LOE:
  type: LockedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rle, :repo_id, :issue_id, :locked_event_id]"
M:
  type: Mannequin
  ready: '2021-09-28'
  templates:
    0: "[:m, :mannequin_id]"
MADE:
  type: MarkedAsDuplicateEvent
  ready: '2021-09-01'
  templates:
    0: "[:rmade, :repo_id, :issue_id, :id]"
MC:
  type: MarketplaceCategory
  ready: '2021-09-07'
  templates:
    0: "[:mc, :marketplace_category_id]"
MCIPE:
  type: MovedColumnsInProjectEvent
  ready: '2021-09-01'
  templates:
    0: "[:rmcip, :repo_id, :issue_id, :id]"
ME:
  type: MergedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rme, :repo_id, :issue_id, :merged_event_id]"
MEE:
  type: MentionedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rm, :repo_id, :issue_id, :id]"
MI:
  type: Milestone
  ready: '2021-07-16'
  templates:
    0: "[:rm, :repo_id, :milestone_id]"
MIE:
  type: MilestonedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rme, :repo_id, :issue_id, :milestoned_event_id]"
ML:
  type: MarketplaceListing
  ready: '2021-07-14'
  templates:
    0: "[:uaml, :user_id, :application_id, :marketplace_listing_id]"
    1: "[:oaml, :organization_id, :application_id, :marketplace_listing_id]"
    2: "[:uoaml, :user_id, :oauth_application_id, :marketplace_listing_id]"
    3: "[:ooaml, :organization_id, :oauth_application_id, :marketplace_listing_id]"
MLP:
  type: MarketplaceListingPlan
  ready: '2021-03-18'
  templates:
    0: "[:mlp, :id]"
MPN:
  type: MobilePushNotificationSchedule
  ready: '2021-06-18'
  templates:
    0: "[:umpn, :user_id, :mobile_push_notification_schedule_id]"
MR:
  type: MigratableResource
  ready: '2021-09-01'
  templates:
    0: "[:mr, :id]"
MS:
  type: MigrationSource
  ready: '2021-09-01'
  templates:
    0: "[:ms, :id]"
O:
  type: Organization
  ready: nil
  templates:
    0: "[:o, :id]"
OI:
  type: OrganizationInvitation
  ready: '2021-06-24'
  templates:
    0: "[:oi, :org_id, :organization_invitation_id]"
OIP:
  type: OrganizationIdentityProvider
  ready: '2021-06-18'
  templates:
    0: "[:ooip, :organization_id, :organization_identity_provider_id]"
P:
  type: Package
  ready: '2021-07-01'
  templates:
    0: "[:rp, :repo_id, :package_id]"
PC:
  type: ProjectColumn
  ready: '2021-03-18'
  templates:
    0: "[:urpc, :user_id, :repository_id, :project_id, :project_column_id]"
    1: "[:orpc, :organization_id, :repository_id, :project_id, :project_column_id]"
    2: "[:upc, :user_id, :project_id, :project_column_id]"
    3: "[:opc, :organization_id, :project_id, :project_column_id]"
    4: "[:rpc, :repository_id, :project_id, :project_column_id]"
PE:
  type: PinnedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rp, :repo_id, :issue_id, :id]"
PF:
  type: PackageFile
  ready: '2021-07-01'
  templates:
    0: "[:rpf, :repo_id, :package_file_id]"
PID:
  type: PinnedDiscussion
  ready: '2021-08-30'
  templates:
    0: "[:rpid, :repo_id, :pinned_discussion_id]"
PIN:
  type: PinnedIssue
  ready: '2021-05-15'
  templates:
    0: "[:urrpi, :user_id, :repository_id, :pinned_issue_id]"
    1: "[:orrpi, :organization_id, :repository_id, :pinned_issue_id]"
    2: "[:pi, :repository_id, :pinned_issue_id]"
PK:
  type: PublicKey
  ready: '2021-05-15'
  templates:
    0: "[:uk, :user_id, :id]"
    1: "[:urrk, :user_id, :repository_id, :id]"
    2: "[:orrk, :organization_id, :repository_id, :id]"
    3: "[:rk, :repository_id, :id]"
PR:
  type: PullRequest
  ready: '2021-09-14'
  templates:
    0: "[:rpr, :repo_id, :pull_request_id]"
PRC:
  type: ProjectCard
  ready: '2021-07-09'
  templates:
    0: "[:oppc, :org_id, :project_id, :project_card_id]"
    1: "[:uppc, :user_id, :project_id, :project_card_id]"
    2: "[:rppc, :repo_id, :project_id, :project_card_id]"
PRO:
  type: Project
  ready: '2021-07-09'
  templates:
    0: "[:op, :org_id, :project_id]"
    1: "[:up, :user_id, :project_id]"
    2: "[:rp, :repo_id, :project_id]"
    3: "[:mp, :mannequin_id, :project_id]"
PRR:
  type: PullRequestReview
  ready: '2021-09-14'
  templates:
    0: "[:rprr, :repo_id, :pull_request_review_id]"
PRRC:
  type: PullRequestReviewComment
  ready: '2021-09-14'
  templates:
    0: "[:rprrc, :repo_id, :id]"
PSH:
  type: Push
  ready: '2021-05-15'
  templates:
    0: "[:urrp, :user_id, :repository_id, :push_id]"
    1: "[:orrp, :organization_id, :repository_id, :push_id]"
    2: "[:rp, :repository_id, :push_id]"
PURC:
  type: PullRequestCommit
  ready: '2021-09-14'
  templates:
    0: "[:r, :repo_id, :pull_id, :commit_oid]"
PV:
  type: PackageVersion
  ready: '2021-07-01'
  templates:
    0: "[:rpv, :repo_id, :package_id, :package_version_id]"
R:
  type: Repository
  ready: nil
  templates:
    0: "[:r, :id]"
RA:
  type: ReleaseAsset
  ready: '2021-09-07'
  templates:
    0: "[:rra, :repo_id, :release_asset_id]"
RAC:
  type: RepositoryAdvisoryComment
  ready: '2021-03-18'
  templates:
    0: "[:rac, :repository_id, :repository_advisory_id, :id]"
RDE:
  type: ReviewDismissedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rrde, :repo_id, :issue_id, :review_dismissed_event_id]"
RE:
  type: Release
  ready: '2021-09-07'
  templates:
    0: "[:rr, :repo_id, :release_id]"
REA:
  type: Reaction
  ready: '2021-09-14'
  templates:
    0: "[:rccr, :repo_id, :commit_comment_id, :reaction_id]"
    1: "[:rir, :repo_id, :issue_id, :reaction_id]"
    2: "[:ricr, :repo_id, :issue_comment_id, :reaction_id]"
    3: "[:rprr, :repo_id, :pull_request_review_id, :reaction_id]"
    4: "[:rprrcr, :repo_id, :pull_request_review_comment_id, :reaction_id]"
    5: "[:rdr, :repo_id, :discussion_id, :reaction_id]"
    6: "[:rdcr, :repo_id, :discussion_comment_id, :reaction_id]"
    7: "[:rrr, :repo_id, :release_id, :reaction_id]"
    8: "[:rrar, :repo_id, :repository_advisory_id, :reaction_id]"
    9: "[:rracr, :repo_id, :repository_advisory_comment_id, :reaction_id]"
    10: "[:ottdr, :org_id, :team_id, :team_discussion_id, :reaction_id]"
    11: "[:ottdcr, :org_id, :team_id, :team_discussion_comment_id, :reaction_id]"
REE:
  type: ReopenedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rre, :repo_id, :issue_id, :reopened_event_id]"
REFE:
  type: ReferencedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rre, :repo_id, :issue_id, :referenced_event_id]"
RFMQE:
  type: RemovedFromMergeQueueEvent
  ready: '2021-09-01'
  templates:
    0: "[:rmde, :repo_id, :issue_id, :id]"
RFPE:
  type: RemovedFromProjectEvent
  ready: '2021-09-01'
  templates:
    0: "[:rrfp, :repo_id, :issue_id, :id]"
RFRE:
  type: ReadyForReviewEvent
  ready: '2021-09-01'
  templates:
    0: "[:rrfre, :repo_id, :issue_id, :ready_for_review_event_id]"
RI:
  type: RepositoryInvitation
  ready: '2021-07-01'
  templates:
    0: "[:ri, :repo_id, :id]"
RM:
  type: RepositoryMigration
  ready: nil
  templates:
    0: "[:rm, :id]"
RR:
  type: ReviewRequest
  ready: '2021-09-01'
  templates:
    0: "[:rrr, :repo_id, :review_request_id]"
RRE:
  type: ReviewRequestedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rrre, :repo_id, :issue_id, :review_requested_event_id]"
RRRE:
  type: ReviewRequestRemovedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rrrre, :repo_id, :issue_id, :review_request_removed_event_id]"
RT:
  type: RepositoryTopic
  ready: '2021-07-02'
  templates:
    0: "[:rt, :repo_id, :repository_topic_id]"
RTE:
  type: RenamedTitleEvent
  ready: '2021-09-01'
  templates:
    0: "[:rrte, :repo_id, :issue_id, :renamed_title_event_id]"
RVA:
  type: RepositoryVulnerabilityAlert
  ready: '2021-09-01'
  templates:
    0: "[:rrva, :repo_id, :repository_vulnerability_alert_id]"
S:
  type: Sponsorship
  ready: '2021-06-02'
  templates:
    0: "[:us, :user_id, :sponsorship_id]"
    1: "[:os, :organization_id, :sponsorship_id]"
SA:
  type: SponsorsActivity
  ready: '2021-06-01'
  templates:
    0: "[:usa, :user_id, :sponsors_activity_id]"
    1: "[:osa, :organization_id, :sponsors_activity_id]"
SC:
  type: StatusContext
  ready: '2021-09-30'
  templates:
    0: "[:rsc, :repo_id, :status_context_id]"
SCR:
  type: StatusCheckRollup
  ready: '2021-09-30'
  templates:
    0: "[:rscr, :repo_id, :oid]"
SE:
  type: SubscribedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rse, :repo_id, :issue_id, :subscribed_event_id]"
SL:
  type: SponsorsListing
  ready: '2021-05-26'
  templates:
    0: "[:usl, :user_id, :sponsors_listing_id]"
    1: "[:osl, :organization_id, :sponsors_listing_id]"
SN:
  type: SponsorshipNewsletter
  ready: '2021-08-21'
  templates:
    0: "[:usn, :user_id, :sponsorship_newsletter_id]"
    1: "[:osn, :organization_id, :sponsorship_newsletter_id]"
SR:
  type: SavedReply
  ready: '2021-06-24'
  templates:
    0: "[:usr, :user_id, :saved_reply_id]"
ST:
  type: SponsorsTier
  ready: '2021-06-04'
  templates:
    0: "[:ust, :user_id, :sponsors_tier_id]"
    1: "[:ost, :organization_id, :sponsors_tier_id]"
T:
  type: Team
  ready: '2021-07-09'
  templates:
    0: "[:t, :organization_id, :id]"
TA:
  type: Tag
  ready: '2021-09-07'
  templates:
    0: "[:t, :repo_id, :oid]"
TD:
  type: TeamDiscussion
  ready: '2021-07-11'
  templates:
    0: "[:ottd, :organization_id, :team_id, :team_discussion_id]"
TDC:
  type: TeamDiscussionComment
  ready: '2021-07-11'
  templates:
    0: "[:ottdc, :organization_id, :team_id, :team_discussion_id, :team_discussion_comment_id]"
TO:
  type: Topic
  ready: '2021-09-21'
  templates:
    0: "[:t, :topic_name]"
TRE:
  type: TransferredEvent
  ready: '2021-09-01'
  templates:
    0: "[:rt, :repo_id, :issue_id, :id]"
U:
  type: User
  ready: nil
  templates:
    0: "[:u, :id]"
UADE:
  type: UnmarkedAsDuplicateEvent
  ready: '2021-09-01'
  templates:
    0: "[:ruad, :repo_id, :issue_id, :id]"
UBE:
  type: UserBlockedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rube, :repo_id, :issue_id, :user_blocked_event_id]"
UCE:
  type: UserContentEdit
  ready: '2021-09-14'
  templates:
    0: "[:rcce, :repo_id, :commit_comment_id, :id]"
    1: "[:rie, :repo_id, :issue_id, :id]"
    2: "[:rice, :repo_id, :issue_comment_id, :id]"
    3: "[:rprr, :repo_id, :pull_request_review_id, :id]"
    4: "[:rprrce, :repo_id, :pull_request_review_comment_id, :id]"
    5: "[:rde, :repo_id, :discussion_id, :id]"
    6: "[:rdce, :repo_id, :discussion_comment_id, :id]"
    7: "[:rrae, :repo_id, :repository_advisory_id, :id]"
    8: "[:rrace, :repo_id, :repository_advisory_comment_id, :id]"
    9: "[:rgce, :user_id, :gist_id, :id]"
    10: "[:ottde, :org_id, :team_id, :team_discussion_id, :id]"
    11: "[:ottdce, :org_id, :team_id, :team_discussion_comment_id, :id]"
UE:
  type: UnsubscribedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rue, :repo_id, :issue_id, :unsubscribed_event_id]"
UNE:
  type: UnassignedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rue, :repo_id, :issue_id, :unassigned_event_id]"
UNLE:
  type: UnlabeledEvent
  ready: '2021-09-01'
  templates:
    0: "[:rue, :repo_id, :issue_id, :unlabeled_event_id]"
UNLOE:
  type: UnlockedEvent
  ready: '2021-09-01'
  templates:
    0: "[:ru, :repo_id, :issue_id, :id]"
UNPE:
  type: UnpinnedEvent
  ready: '2021-09-01'
  templates:
    0: "[:rue, :repo_id, :issue_id, :unpinned_event_id]"
US:
  type: UserStatus
  ready: '2021-06-25'
  templates:
    0: "[:us, :user_id, :user_status_id]"
WFR:
  type: WorkflowRun
  ready: '2021-05-15'
  templates:
    0: "[:urwr, :user_id, :repository_id, :workflow_run_id]"
    1: "[:orwr, :organization_id, :repository_id, :workflow_run_id]"
    2: "[:wr, :repository_id, :id]"
